# Use the official Python image from the Docker Hub
FROM python:3.12-slim

# Install PostgresSQL dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

# Expose the port the app runs on
EXPOSE 5050

# Define the command to run the application
CMD ["uvicorn", "source.main:app", "--host", "0.0.0.0", "--port", "5050"]
