services:
  server:
    build: .
    ports:
      - "5050:5050"
    volumes:
      - ./:/app

    environment:
      - UPLOAD_FOLDER=/app/uploads
  database:
   image: postgres
   restart: always
   ports:
    - "5432:5432"
   environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres
